
package webservice.list;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "List", targetNamespace = "http://www.webservice.list")
@XmlSeeAlso({
    FactoryOfObeject.class
})
public interface List {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.webservice.list", className = "webservice.list.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.webservice.list", className = "webservice.list.AddResponse")
    @Action(input = "http://www.webservice.list/List/addRequest", output = "http://www.webservice.list/List/addResponse")
    public String add(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.webservice.list", className = "webservice.list.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.webservice.list", className = "webservice.list.RegisterResponse")
    @Action(input = "http://www.webservice.list/List/registerRequest", output = "http://www.webservice.list/List/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clear", targetNamespace = "http://www.webservice.list", className = "webservice.list.Clear")
    @ResponseWrapper(localName = "clearResponse", targetNamespace = "http://www.webservice.list", className = "webservice.list.ClearResponse")
    @Action(input = "http://www.webservice.list/List/clearRequest", output = "http://www.webservice.list/List/clearResponse")
    public String clear(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://www.webservice.list", className = "webservice.list.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://www.webservice.list", className = "webservice.list.DeleteResponse")
    @Action(input = "http://www.webservice.list/List/deleteRequest", output = "http://www.webservice.list/List/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://www.webservice.list", className = "webservice.list.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://www.webservice.list", className = "webservice.list.QueryResponse")
    @Action(input = "http://www.webservice.list/List/queryRequest", output = "http://www.webservice.list/List/queryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
